-- AlterTable
ALTER TABLE "InterviewSession" ADD COLUMN IF NOT EXISTS "integrityCameraMoveCount" INTEGER NOT NULL DEFAULT 0;

-- AlterEnum
ALTER TYPE "ProctoringSignalType" ADD VALUE IF NOT EXISTS 'SECONDARY_CAMERA_MOVED';
ALTER TYPE "ProctoringSignalType" ADD VALUE IF NOT EXISTS 'SECONDARY_NO_FACE';
ALTER TYPE "ProctoringSignalType" ADD VALUE IF NOT EXISTS 'SECONDARY_MULTIPLE_FACES';
ALTER TYPE "ProctoringSignalType" ADD VALUE IF NOT EXISTS 'SECONDARY_LOOKING_AT_DEVICE';
