-- AlterEnum
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_MULTIPLE_PERSONS';
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_PERSON_RETURNED_TO_ONE';
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_PERSON_INTERACTION';
