-- AlterEnum
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_PERSON_MOVED';
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_PERSON_RETURNED';
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_ATTENTION_DEVIATION';
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_DEVICE_VISIBLE';
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_DEVICE_REMOVED';
ALTER TYPE "ProctoringSignalType" ADD VALUE 'SECONDARY_DEVICE_INTERACTION';
